#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

caseName=$(basename $(dirname $(readlink -f "$0")))
touch ${caseName}.foam
restore0Dir

# Generate base mesh
runApplication blockMesh

#cd moveDyn

#cp -pr ../constant/polyMesh constant/

#pwd

#runApplication moveDynamicMesh


#cd ..

#cp -pr moveDyn/1/polyMesh/* constant/polyMesh/

# Set initial free surface
runApplication setFields

# Run case
#runApplication decomposePar
#runParallel $(getApplication)
runApplication $(getApplication)

# Reconstruct
##runApplication reconstructPar

# Generate results files (png's and pdf in figs/ folder)
##./generateResultFigures

#------------------------------------------------------------------------------
